{
  # Do not modify this file!  It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.  Please make changes
  # to /etc/nixos/configuration.nix instead.
  flake.nixosModules.redmi =
    {
      config,
      lib,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usbhid"
        "rtsx_pci_sdmmc"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/31b21550-762a-41e4-a676-64b363862282";
        fsType = "btrfs";
        options = [ "subvol=root" ];
      };

      fileSystems."/nix" = {
        device = "/dev/disk/by-uuid/31b21550-762a-41e4-a676-64b363862282";
        fsType = "btrfs";
        options = [ "subvol=nix" ];
      };

      fileSystems."/var" = {
        device = "/dev/disk/by-uuid/31b21550-762a-41e4-a676-64b363862282";
        fsType = "btrfs";
        options = [ "subvol=var" ];
      };

      fileSystems."/data" = {
        device = "/dev/disk/by-uuid/31b21550-762a-41e4-a676-64b363862282";
        fsType = "btrfs";
        options = [ "subvol=root/data" ];
      };

      fileSystems."/home" = {
        device = "/dev/disk/by-uuid/31b21550-762a-41e4-a676-64b363862282";
        fsType = "btrfs";
        options = [ "subvol=home" ];
      };

      fileSystems."/data/Games" = {
        device = "/dev/disk/by-uuid/31b21550-762a-41e4-a676-64b363862282";
        fsType = "btrfs";
        options = [ "subvol=root/data/Games" ];
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/B91A-79F9";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };

      swapDevices = [
        { device = "/dev/disk/by-uuid/dadd8a61-24d4-4969-8e36-86ad5610c60d"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
